server:
  port: 8761

spring:
  application:
    name: eureka-server

# Allow optional config server import so service can run when config-server is available
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
